name: Deploy Dockerized Express App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Check if SSH_PRIVATE_KEY is set
          if [ -z "${SSH_PRIVATE_KEY}" ]; then
            echo "Error: SSH_PRIVATE_KEY is not set. Exiting."
            exit 1
          else
            echo "SSH_PRIVATE_KEY is set (value hidden for security)."
          fi

          # Debug: Print SSH key to confirm it's being set (remove or comment out in production)
          echo "${SSH_PRIVATE_KEY}" | tr -d '\n' | head -c 10 && echo "..."

          # Create .ssh directory and set proper permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write SSH private key to file and secure it
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/oceanKey
          chmod 600 ~/.ssh/oceanKey

          # Debug to confirm file creation and permissions
          ls -la ~/.ssh

          # Add server to known_hosts
          ssh-keyscan -H "${SERVER_IP}" >> ~/.ssh/known_hosts

          # SSH into the server and deploy the application
          ssh -i ~/.ssh/oceanKey "${SERVER_USER}"@"${SERVER_IP}" << 'EOF'
            set -e  # Exit immediately if a command fails

            # Ensure the project directory exists
            if [ ! -d "/www/my-app/ISTE422_EX06" ]; then
              git clone https://github.com/ColinChomas/ISTE422_EX06.git /www/my-app/ISTE422_EX06
            fi

            cd /www/my-app/ISTE422_EX06

            # Pull the latest changes from the repository
            git pull origin main

            # Install dependencies and start/restart the app
            npm install
            pm2 start index.js --name my-app || pm2 restart my-app
          EOF