name: Deploy Dockerized Express App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run:
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/oceanKey
          chmod 600 ~/.ssh/oceanKey

          ssh-keyscan -H ${{secrets.SERVER_IP}} >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/oceanKey ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}} << 'EOF'
            cd /www/my-app/ISTE422_EX06 || git clone https://github.com/ColinChomas/ISTE422_EX06.git /root/www/my-app/
            cd /www/my-app/ISTE422_EX06
            git pull origin main
            npm install
            pm2 start index.js --name my-app || pm2 restart my-app
          EOF

        